redis-rb/redis-cluster-client

- README.md
- lib/redis_client/cluster.rb
- lib/redis_client/cluster/node.rb
- lib/redis_client/cluster_config.rb
- test/redis_client/cluster/test_node.rb
> Enhance performance to use thread and ensure thread safety

- README.md
- lib/redis_client/cluster.rb
- lib/redis_client/cluster/command.rb
- lib/redis_client/cluster/errors.rb
- lib/redis_client/cluster/key_slot_converter.rb
- lib/redis_client/cluster/node.rb
- test/redis_client/cluster/test_command.rb
- test/redis_client/cluster/test_key_slot_converter.rb
- test/redis_client/cluster/test_node.rb
- test/redis_client/test_cluster.rb
- test/test_against_cluster_broken.rb
> Fix node down test cases

- lib/redis_client/cluster.rb
- lib/redis_client/cluster/node.rb
- test/redis_client/test_cluster.rb
- test/test_against_cluster_broken.rb
- test/test_against_cluster_state.rb
> Fix blocking call bug and add node down test cases for primary node

- lib/redis_client/cluster/command.rb
> Fix command information loading logic

- lib/redis_client/cluster/node.rb
https://blog.arkency.com/2014/01/ruby-to-enum-for-enumerator/
> Refactor a method for iterate raw clients

- .github/workflows/test.yaml
- Gemfile
> Enable hiredis test

- lib/redis_client/cluster.rb
- lib/redis_client/cluster/pipeline.rb
- lib/redis_client/cluster/pubsub.rb
- lib/redis_client/cluster/router.rb
- test/test_against_cluster_broken.rb
- test/test_against_cluster_state.rb
> Refactor codes for command routing

- .github/workflows/test.yaml
- Rakefile
- test/bench_command.rb
- test/benchmark_helper.rb
> Add benchmark test

- lib/redis_client/cluster.rb
- lib/redis_client/cluster/command.rb
- lib/redis_client/cluster/router.rb
- lib/redis_client/cluster_config.rb
- test/redis_client/cluster/test_command.rb
- test/redis_client/test_cluster.rb
- test/redis_client/test_cluster_config.rb
> feat: support compatibility with redis gem

- docs/class_diagrams_redis_cluster_client.md
- lib/redis_client/cluster.rb
- lib/redis_client/cluster/pipeline.rb
- lib/redis_client/cluster/pub_sub.rb
- lib/redis_client/cluster/router.rb
https://github.com/redis-rb/redis-client#type-support
> feat: support more compatibility with redis client

- .github/workflows/test.yaml
- Rakefile
- docker-compose.latency.yaml
- lib/redis_client/cluster_config.rb
- test/bench_command.rb
- test/redis_client/test_cluster.rb
- test/redis_client/test_cluster_config.rb
> fix: the replica affinity option is not working

- .rubocop.yml
- lib/redis_client/cluster/node/latency_replica.rb
- lib/redis_client/cluster/pipeline.rb
- lib/redis_client/cluster/router.rb
- test/redis_client/test_cluster.rb
- test/test_against_cluster_state.rb
> fix: handle redirection errors in pipelining

- .rubocop.yml
- lib/redis_client/cluster/node.rb
- lib/redis_client/cluster/node/latency_replica.rb
- lib/redis_client/cluster/node/random_replica.rb
- lib/redis_client/cluster/router.rb
- lib/redis_client/cluster_config.rb
- test/test_against_cluster_state.rb
> test: fix resharding test for scale reading

- lib/redis_client/cluster/node.rb
- lib/redis_client/cluster/router.rb
- test/cluster_controller.rb
- test/prof_mem.rb
- test/redis_client/cluster/node/test_latency_replica.rb
- test/redis_client/cluster/node/test_primary_only.rb
- test/redis_client/cluster/node/test_random_replica.rb
- test/redis_client/cluster/node/testing_topology_mixin.rb
- test/redis_client/cluster/test_node.rb
> perf: use struct instead of hash for memory efficiency

- lib/redis_client/cluster/node.rb
- lib/redis_client/cluster/node/latency_replica.rb
- lib/redis_client/cluster/router.rb
- test/cluster_controller.rb
- test/redis_client/cluster/test_node.rb
- test/redis_client/test_cluster.rb
> fix: several issues

- Rakefile
- lib/redis_client/cluster/node/latency_replica.rb
- lib/redis_client/cluster/pipeline.rb
> fix: use monkey patch instead of calling Object#send and Object#instance_variable_get

- test/redis_client/test_cluster.rb
> test: add sharded pub/sub cases

- .github/workflows/test.yaml
The following feature is not working for me. Am I missing something? GitHub Actions doesn't generate expected combinations.
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymatrixinclude
> ci: aggregate jobs

- .github/workflows/test.yaml
- lib/redis_client/cluster/router.rb
- lib/redis_client/cluster_config.rb
- redis-cluster-client.gemspec
- test/cluster_controller.rb
- test/redis_client/test_cluster.rb
- test/testing_constants.rb
* https://github.com/redis-rb/redis-client/pull/70
> feat: support circuit breaker

- lib/redis_client/cluster/node/latency_replica.rb
> chore: correct a constant for dummy latency in measurement

- lib/redis_client/cluster/pub_sub.rb
- test/redis_client/test_cluster.rb
* #214
* #215
* #217
* #220
* The above poor implementation takes additional wasting time for waiting to be received new message.
> fix: enbuged for Pub/Sub

- lib/redis_client/cluster/pub_sub.rb
* #214
* #215
* #217
* #220
* #222
* Subscription should be balanced in all channels.
> fix: balancing act for subscription

- lib/redis_client/cluster/pub_sub.rb
https://redis.io/commands/ssubscribe/
> Note that this command can also return a `-MOVED` redirect.
> fix: client should handle redirection for sharded pubsub

- test/redis_client/test_cluster.rb
> test: enable skipped test cases

- lib/redis_client/cluster/pub_sub.rb
> perf: lessen wasting time for pubsub

- lib/redis_client/cluster/pub_sub.rb
> perf: lessen wasting memory allocation for Pub/Sub

- lib/redis_client/cluster/pub_sub.rb
> perf: lessen cpu usage in loop for Pub/Sub

- lib/redis_client/cluster/pub_sub.rb
- test/redis_client/test_cluster.rb
* Performance enhancement for subscription by using SizedQueue for efficiency
* Changing behavior for the error handling on `#next_event`
* Raise the error instead of returning the error object
> fix: Pub/Sub with performance enhancement and changing error handling

- .github/workflows/test.yaml
> ci: fix flaky test

- lib/redis_client/cluster/pub_sub.rb
- redis-cluster-client.gemspec
Also, this PR fixes a bug in Pub/Sub.
> build: release 0.7.3

- lib/redis_client/cluster/pipeline.rb
- test/test_against_cluster_state.rb
The pipelining support works by fanning out queries to the appropriate nodes in parallel in a scatter stage, and then, during the gather stage, detecting where redirecting is required and issuing the commands again on the redirected-to node.
The gathering happens in parallel to the scattering, however; it's possible for the gather thread to issue a redirection on a connection still in use by a scatter thread, resulting in pandemonium.
I've committed a testcase with this patch which, at least on my machine, was failing because instead of getting "OK" in response to the SET commands, it would get a hash which was _actually_ a response to a HELLO command issued on the same connection by mistake.
This patch fixes things by deferring the redirections until after all of the initial pipelines …
> Fix #pipelined concurrently using the same Redis connection

- test/redis_client/test_cluster.rb
But It won't affect the results.
> test: fix a wrong test case

- lib/redis_client/cluster/optimistic_locking.rb
> fix: unwatch should be called only if an error occurred during the transaction

- lib/redis_client/cluster/router.rb
- test/redis_client/test_cluster.rb
> fix: add a dedicated implementation for the watch command, it may be used by the redis gem

- test/test_concurrency.rb
> test: concurrency for the transaction

- redis-cluster-client.gemspec
> build: release 0.11.1

- lib/redis_client/cluster/pub_sub.rb
- lib/redis_client/cluster/router.rb
The following fix was insufficient.
* #379
Also the following issue is related.
* #368
> fix: ensure recoverability from cluster down for pubsub and transaction

- bin/pubsub
- lib/redis_client/cluster/pub_sub.rb
- lib/redis_client/cluster/router.rb
- test/cluster_controller.rb
The following fix was insufficient.
* #379
* #381
Also the following issue is related.
* #368
> fix: ensure recoverability for pubsub

- redis-cluster-client.gemspec
> build: release 0.11.3

- redis-cluster-client.gemspec
> build: release 0.11.4

- .github/workflows/test.yaml
- Rakefile
- bin/pubsub
- bin/singlepiptx
- test/test_against_cluster_down.rb
> test: add a case for the recoverability from cluster down

- test/test_against_cluster_broken.rb
> test: no need to wait uselessly

- redis-cluster-client.gemspec
> build: release 0.12.0

- lib/redis_client/cluster_config.rb
- test/redis_client/test_cluster_config.rb
> fix: set an ID option to a cluster config for the compatibility

- lib/redis_client/cluster/node.rb
- redis-cluster-client.gemspec
* https://github.com/redis-rb/redis-client/pull/230
Unfortunately, we have some monkey patches.
> fix: follow the library changes we depend on

- README.md
> Add a badge to this wiki in the repo's README file to auto refresh the wiki weekly with the latest code.
> docs: add a badge for DeepWiki
