- test/redis_client/test_cluster.rb
```
1) Failure:
RedisClient::TestCluster::Pooled#test_dedicated_commands [/home/runner/work/redis-cluster-client/redis-cluster-client/test/redis_client/test_cluster.rb:180]:
Case: WAIT 1 1.
Expected: 3
Actual: 2
```
> test: fix a freaky test case

- lib/redis_client/cluster/router.rb
There might be some cases that some nodes or redis-client reply with unexpected type values.
```
1) Error:
RedisClient::TestCluster::PrimaryOnly#test_dedicated_commands:
ArgumentError: comparison of String with 1 failed
/home/runner/work/redis-cluster-client/redis-cluster-client/lib/redis_client/cluster/router.rb:37:in `sort'
/home/runner/work/redis-cluster-client/redis-cluster-client/lib/redis_client/cluster/router.rb:37:in `send_command'
/home/runner/work/redis-cluster-client/redis-cluster-client/lib/redis_client/cluster.rb:21:in `call'
/home/runner/work/redis-cluster-client/redis-cluster-client/test/redis_client/test_cluster.rb:174:in `block (2 levels) in test_dedicated_commands'
/home/runner/work/redis-cluster-client/redis-cluster-client/test/redis_client/test_cluster.rb:180:in `block …
```
> fix: prevent comparison errors

- lib/redis_client/cluster.rb
- lib/redis_client/cluster/node.rb
- lib/redis_client/cluster/pipeline.rb
- lib/redis_client/cluster/pub_sub.rb
- lib/redis_client/cluster/router.rb
- lib/redis_client/cluster_config.rb
- test/redis_client/cluster/test_node.rb
- test/redis_client/test_cluster.rb
Counterpart to https://github.com/redis-rb/redis-client/commit/ef44f0862a186293f0c56213f828ad7a19f09418.
That's the interface `redis-rb` will use, as it avoid splating arguments all the time. It also happens to simplify `redis-cluster-client` IMO.
> Implement the `call_v` style interfaces.

- lib/redis_client/cluster/router.rb
That's how `redis-client` behaves.
> Do not retry `blocking_call` on ReadTimeout

- lib/redis_client/cluster.rb
- lib/redis_client/cluster_config.rb
- test/redis_client/test_cluster.rb
It's needed by redis-rb for blocking commands
> Expose #config to allow accessing read_timeout

- lib/redis_client/cluster/node.rb
- lib/redis_client/cluster/pipeline.rb
- test/redis_client/test_cluster.rb
* https://shopify.engineering/ruby-execution-models
* https://ivoanjo.me/blog/2022/07/17/tracing-ruby-global-vm-lock/
* https://workingwithruby.com/wwrt/how_many_threads/
* https://redis.io/docs/reference/cluster-spec/
* > High performance and linear scalability up to 1000 nodes.
```
$ grep Thread.new lib -r
lib/redis_client/cluster/pipeline.rb:            Thread.new(@router, k, v) do |router, node_key, rows|
lib/redis_client/cluster/node.rb:              Thread.new(raw_client, (MAX_THREADS * 2 * chuncked_idx) + idx) do |cli, i|
lib/redis_client/cluster/node.rb:            Thread.new(k, v) do |node_key, client|
```
> Reduce consumption of threads

- README.md
- Rakefile
- docker-compose.nat.yaml
- docs/class_diagrams_redis_cluster_client.md
- lib/redis_client/cluster.rb
- lib/redis_client/cluster/node.rb
- lib/redis_client/cluster/node/latency_replica.rb
- lib/redis_client/cluster/node/nearest_replica.rb
- lib/redis_client/cluster/node/primary_only.rb
- lib/redis_client/cluster/node/random_replica.rb
- lib/redis_client/cluster/node/replica_mixin.rb
- lib/redis_client/cluster/pipeline.rb
- lib/redis_client/cluster/router.rb
- lib/redis_client/cluster_config.rb
- test/cluster_controller.rb
- test/redis_client/cluster/node/test_latency_replica.rb
- test/redis_client/cluster/node/test_primary_only.rb
- test/redis_client/cluster/node/test_random_replica.rb
- test/redis_client/cluster/test_node.rb
- test/redis_client/test_cluster.rb
- test/redis_client/test_cluster_config.rb
- test/test_against_cluster_scale.rb
closes #96
```ruby
RedisClient.cluster(replica: true, replica_affinity: :latency).new_client
```
The client becomes able to prioritize replicas by latency.
> feat: add replica affinity option

- .github/workflows/test.yaml
- Gemfile
- Rakefile
- lib/redis_client/cluster.rb
- lib/redis_client/cluster/command.rb
- lib/redis_client/cluster/pipeline.rb
- test/prof_mem.rb
```
Total allocated: 9068094 bytes (68763 objects)
```
```
allocated memory by location
5645840  redis-cluster-client/lib/redis_client/cluster/pipeline.rb:23
546680  redis-client-0.8.1/lib/redis_client/ruby_connection/buffered_io.rb:97
320000  redis-cluster-client/lib/redis_client/cluster/command.rb:75
262224  redis-cluster-client/lib/redis_client/cluster/node.rb:202
201240  redis-client-0.8.1/lib/redis_client/ruby_connection/resp3.rb:95
184704  redis-client-0.8.1/lib/redis_client/ruby_connection/resp3.rb:147
182898  redis-client-0.8.1/lib/redis_client/ruby_connection/buffered_io.rb:104
160280  redis-client-0.8.1/lib/redis_client/command_builder.rb:9
160000  redis-cluster-client/lib/redis_client/cluster/command.rb:82
160000 …
```
> perf: reduce memory allocations for pipelining

- docs/class_diagrams_redis_client.md
- docs/class_diagrams_redis_cluster_client.md
- lib/redis_client/cluster/command.rb
- lib/redis_client/cluster/pipeline.rb
- test/prof_mem.rb
```
Total allocated: 3594279 bytes (64765 objects)
```
```
allocated memory by location
546600  redis-client-0.8.1/lib/redis_client/ruby_connection/buffered_io.rb:97
320000  redis-cluster-client/lib/redis_client/cluster/command.rb:75
262224  redis-cluster-client/lib/redis_client/cluster/node.rb:202
201240  redis-client-0.8.1/lib/redis_client/ruby_connection/resp3.rb:95
184704  redis-client-0.8.1/lib/redis_client/ruby_connection/resp3.rb:147
182898  redis-client-0.8.1/lib/redis_client/ruby_connection/buffered_io.rb:104
160280  redis-client-0.8.1/lib/redis_client/command_builder.rb:9
160000  redis-cluster-client/lib/redis_client/cluster/command.rb:82
160000  redis-cluster-client/lib/redis_client/cluster/pipeline.rb:69
159600 …
```
> perf: reduce memory allocations for string and array

- lib/redis_client/cluster/command.rb
- lib/redis_client/cluster/normalized_cmd_name.rb
- lib/redis_client/cluster/router.rb
- test/bench_command.rb
- test/prof_mem.rb
- test/redis_client/cluster/test_normalized_cmd_name.rb
- test/redis_client/test_cluster.rb
- test/test_against_cluster_broken.rb
- test/test_against_cluster_scale.rb
- test/test_against_cluster_state.rb
```
Total allocated: 3923319 bytes (60737 objects)
```
```
allocated memory by location
677376  redis-client-0.8.1/lib/redis_client/ruby_connection/resp3.rb:54
546680  redis-client-0.8.1/lib/redis_client/ruby_connection/buffered_io.rb:97
338688  redis-client-0.8.1/lib/redis_client/ruby_connection/resp3.rb:55
262224  redis-cluster-client/lib/redis_client/cluster/node.rb:202
240000  redis-cluster-client/lib/redis_client/cluster/router.rb:68
201240  redis-client-0.8.1/lib/redis_client/ruby_connection/resp3.rb:95
184704  redis-client-0.8.1/lib/redis_client/ruby_connection/resp3.rb:147
182898 …
```
> perf: reduce memory allocations

- lib/redis_client/cluster/command.rb
- test/redis_client/cluster/test_command.rb
* #137
```
Total allocated: 2721324 bytes (44800 objects)
Total retained:  120 bytes (3 objects)
```
```
allocated memory by gem
1883950  redis-client-0.9.0
565500  redis-cluster-client/lib
160928  other
110946  x64/lib
```
```
allocated memory by file
792800  redis-client-0.9.0/lib/redis_client/ruby_connection/resp3.rb
779022  redis-client-0.9.0/lib/redis_client/ruby_connection/buffered_io.rb
352676  redis-cluster-client/lib/redis_client/cluster/node.rb
280280  redis-client-0.9.0/lib/redis_client/command_builder.rb
160440 …
```
> perf: use struct instead of hash for memory consumption

- lib/redis_client/cluster/node.rb
- test/redis_client/cluster/test_node.rb
closes #137
```
Total allocated: 2747715 bytes (44836 objects)
Total retained:  120 bytes (3 objects)
```
```
allocated memory by gem
1941308  redis-client-0.9.0
530396  redis-cluster-client/lib
160928  other
115083  x64/lib
```
```
allocated memory by file
836380  redis-client-0.9.0/lib/redis_client/ruby_connection/buffered_io.rb
792800  redis-client-0.9.0/lib/redis_client/ruby_connection/resp3.rb
355556  redis-cluster-client/lib/redis_client/cluster/node.rb
280280  redis-client-0.9.0/lib/redis_client/command_builder.rb
160440 …
```
> perf: optimize memory allocation for slot-node-mapping array

- lib/redis_client/cluster/pipeline.rb
When a pipeline is executed each thread that is spawned immediately hints to the scheduler it should pass execution to another thread before it attempts to do any work. I was unsure of the reason for this and thought it might be causing unnecessary context switches and/or other overhead. I attempted to do quick look through the gem's history to see if there was a specific reason for using `Thread.pass` but didn't notice any. I wanted to benchmark the throughput of running a pipeline with and without thread pass so I put together the following benchmark:
```ruby
require 'benchmark/ips'
require 'redis-cluster-client'
rc = RedisClient.cluster(nodes: ['redis://node1:6379']).new_client
PIPE_GET_KEYS = %w[test_1 test_2 test_3 test_4 test_5 test_6 test_7 test_8 test_9 test_10]
PIPE_GET_VALUES = …
```
> perf: don't immediately Thread.pass in Pipeline#execute when there is work to do

- lib/redis_client/cluster/command.rb
Use frozen strings for `extract_hash_tag`
```
require "benchmark/ips"
require "securerandom"
EMPTY_STRING = "".freeze
LEFT_BRACKET = "{".freeze
RIGHT_BRACKET = "}".freeze
def random_key
(rand * 10).to_i % 2 == 0 ? SecureRandom.hex(32) : "{" << SecureRandom.hex(32) << "}"
end
def slow
100000.times {
key = random_key
s = key.index('{')
e = key.index('}', s.to_i + 1)
return EMPTY_STRING if s.nil? || e.nil?
key[s + 1..e - 1]
}
end
def fast
100000.times {
key = random_key
s = key.index(LEFT_BRACKET)
return EMPTY_STRING if s.nil?
e = key.index(RIGHT_BRACKET, s + 1)
return EMPTY_STRING if e.nil?
key[s + 1..e - 1]
}
end
Benchmark.ips do |x|
x.report("fast") { fast }
x.report("slow") { slow }
x.compare!
end
```
Result:
```
fast    54.463k i/100ms …
```
> perf: faster extract_hash_tag

- lib/redis_client/cluster/pipeline.rb
- redis-cluster-client.gemspec
* #166
> undefined method `call_pipelined' for RedisClient::Middlewares:Class
> fix: pipelined broken due to redis-client v0.10

- .github/workflows/test.yaml
> ci: use environment variables instead of set-output commands

- .github/workflows/test.yaml
* https://github.com/redis/redis/releases/tag/7.0.5
* https://github.com/redis/redis/releases/tag/7.0.4
* https://github.com/redis/redis/releases/tag/7.0.3
* https://github.com/redis/redis/releases/tag/7.0.2
> ci: bump redis server version from 7.0.1 to 7.0.5 for testing

- lib/redis_client/cluster/router.rb
- test/redis_client/test_cluster.rb
`SCRIPT EXISTS sha1 sha2 ...` must check all nodes. If a node has lost the script from its cache (a node restarted, etc.) we should know about it.
> fix: SCRIPT EXISTS must check all nodes

- lib/redis_client/cluster/node.rb
- lib/redis_client/cluster/node/latency_replica.rb
- lib/redis_client/cluster/pipeline.rb
- test/redis_client/cluster/test_normalized_cmd_name.rb
- test/test_concurrency.rb
```
$ grep thread_variable_get lib/ test/ -rl | xargs sed -i -r -e 's#\.thread_variable_get\((:[_a-z]+)\)#[\1]#g'
$ grep thread_variable_set lib/ test/ -rl | xargs sed -i -r -e 's#\.thread_variable_set\((:[_a-z0-9]+), (.+)\)#[\1] = \2#g'
$ grep thread_variable lib/ test/ -rl | xargs sed -i -e 's#thread_variable#key#g'
```
> fix: use fiber local storage instead of thread local storage

- lib/redis_client/cluster/router.rb
- test/redis_client/test_cluster.rb
Since redis gem's CI is failing:
https://github.com/redis/redis-rb/actions/runs/3931275812/jobs/6722318987
```
1) Error:
TestClusterCommandsOnScripting#test_script_exists:
TypeError: no implicit conversion of true into Array
/home/runner/work/redis-rb/redis-rb/vendor/bundle/ruby/2.7.0/gems/redis-cluster-client-0.4.0/lib/redis_client/cluster/router.rb:270:in `transpose'
/home/runner/work/redis-rb/redis-rb/vendor/bundle/ruby/2.7.0/gems/redis-cluster-client-0.4.0/lib/redis_client/cluster/router.rb:270:in `send_script_command'
/home/runner/work/redis-rb/redis-rb/vendor/bundle/ruby/2.7.0/gems/redis-cluster-client-0.4.0/lib/redis_client/cluster/router.rb:50:in `send_command'
/home/runner/work/redis-rb/redis-rb/vendor/bundle/ruby/2.7.0/gems/redis-cluster-client-0.4.0/lib/redis_client/cluster.rb:3 …
```
> fix: delay transformation of reply data to prevent errors while converting

- lib/redis_client/cluster/router.rb
- test/redis_client/test_cluster.rb
This is a enbug by:
* #190
https://github.com/redis/redis-rb/actions/runs/4077433120/jobs/7026449200
```
1) Error:
TestClusterCommandsOnServer#test_client_list:
NoMethodError: undefined method `lines' for #<Array:0x0000564cb2ac7a38>
/home/runner/work/redis-rb/redis-rb/lib/redis/commands/server.rb:42:in `block in client'
/home/runner/work/redis-rb/redis-rb/vendor/bundle/ruby/2.7.0/gems/redis-cluster-client-0.4.1/lib/redis_client/cluster/router.rb:17:in `block in <class:Router>'
/home/runner/work/redis-rb/redis-rb/vendor/bundle/ruby/2.7.0/gems/redis-cluster-client-0.4.1/lib/redis_client/cluster/router.rb:243:in `then'
/home/runner/work/redis-rb/redis-rb/vendor/bundle/ruby/2.7.0/gems/redis-cluster-client-0.4.1/lib/redis_client/cluster/router.rb:243:in `send_client_command' …
```
> fix: a bug for client list command

- lib/redis_client/cluster/node.rb
- test/cluster_controller.rb
- test/redis_client/cluster/test_node.rb
- test/test_against_cluster_scale.rb
This PR proposes to use `hostname:ip` for the node key instead of `ip:port` if `cluster-preferred-endpoint-type` is set to `hostname` while running a Redis Cluster on Redis v7.0. 
This allows the client to handle redirection responses which uses the preferred endpoint (e.g. `MOVED <slot number> <preferred endpoint>:<port>`) if the cluster is configured to use `hostname`.
Resolves https://github.com/redis-rb/redis-cluster-client/issues/205
> fix: use hostname in node_key if present in CLUSTER NODES

- lib/redis_client/cluster/pub_sub.rb
- test/redis_client/test_cluster.rb
> fix: client should be able to subscribe multiple channels for Pub/Sub

- lib/redis_client/cluster/pub_sub.rb
- test/redis_client/test_cluster.rb
* #214
* #215
* client should return nil if messages are none
* https://github.com/redis-rb/redis-client#publish--subscribe
> fix: broken behavior for Pub/Sub

- lib/redis_client/cluster/node.rb
This PR enables users to configure `MAX_STARTUP_SAMPLE` via the environment variable `REDIS_CLIENT_MAX_STARTUP_SAMPLE`, defaulting to 3 (a pretty reasonable baseline default since the smallest possible cluster size is 3). 
Credits to suggestion in https://github.com/redis-rb/redis-cluster-client/pull/242#issuecomment-1677163041
This PR resolves the spike in initialization load in https://github.com/redis-rb/redis-cluster-client/issues/241 by allowing users to configure a sample size more appropriate for their clusters.
Note/caveat: when it comes to sampling, it is always probabilistic. To combat the risk of under-sampling, users could configure their application to retry on `::RedisClient::Cluster::InitialSetupError` and reload using another sample.
> fix: allow configurable max startup samples

- .github/workflows/test.yaml
https://github.com/redis-rb/redis-cluster-client/actions/runs/5861282714/job/15891056124
```
1) Failure:
TestAgainstClusterScale#test_02_scale_in [/home/runner/work/redis-cluster-client/redis-cluster-client/test/test_against_cluster_scale.rb:65]:
Case: number of nodes.
Expected: 6
Actual: 1
```
https://github.com/redis-rb/redis-cluster-client/actions/runs/5861408040/job/15891415383
```
1) Failure:
TestAgainstClusterScale#test_02_scale_in [/home/runner/work/redis-cluster-client/redis-cluster-client/test/test_against_cluster_scale.rb:65]:
Case: number of nodes.
Expected: 6
Actual: 1
```
related to:
* #243
> ci: configure REDIS_CLIENT_MAX_STARTUP_SAMPLE for flaky test cases

- .github/workflows/test.yaml
* https://redis.io/download/
* https://github.com/redis/redis/releases/tag/7.2.0
* https://hub.docker.com/_/redis/
* https://github.com/docker-library/redis
Jump the gun.
> ci: test against redis 7.2

- Gemfile
- Rakefile
- lib/redis_client/cluster.rb
- lib/redis_client/cluster/concurrent_worker.rb
- lib/redis_client/cluster_config.rb
- test/ips_pipeline.rb
Not as fast as I thought.
```
$ bundle exec rake ips
on_demand    29.000  i/100ms
pooled    32.000  i/100ms
on_demand    303.783  (± 9.5%) i/s -      1.508k in   5.024205s
pooled    324.667  (± 3.4%) i/s -      1.632k in   5.032874s
Comparison:
pooled:      324.7 i/s
on_demand:      303.8 i/s - same-ish: difference falls within error
```
> feat: add concurrent worker model option

- .github/workflows/test.yaml
- lib/redis_client/cluster/concurrent_worker.rb
- lib/redis_client/cluster/concurrent_worker/on_demand.rb
- lib/redis_client/cluster/concurrent_worker/pooled.rb
- test/ips_single.rb
- test/redis_client/cluster/test_node.rb
```
pipelined: ondemand    68.000  i/100ms
pipelined: pooled    63.000  i/100ms
pipelined: envoy    41.000  i/100ms
pipelined: cproxy    49.000  i/100ms
pipelined: ondemand    690.077  (± 5.4%) i/s -      3.468k in   5.043327s
pipelined: pooled    716.485  (± 8.7%) i/s -      3.591k in   5.063423s
pipelined: envoy    411.958  (± 7.5%) i/s -      2.050k in   5.014065s
pipelined: cproxy    400.665  (±22.7%) i/s -      1.911k in   5.040554s
Comparison:
pipelined: pooled:      716.5 i/s
pipelined: ondemand:      690.1 i/s - same-ish: …
```
> chore: add some benchmarks for iteration per seconds

- .github/workflows/test.yaml
- test/ips_pipeline.rb
- test/ips_single.rb
* #266
```
pipelined: ondemand    47.000  i/100ms
pipelined: pooled    51.000  i/100ms
pipelined: envoy    51.000  i/100ms
pipelined: cproxy    34.000  i/100ms
pipelined: ondemand    485.444  (± 3.7%) i/s -      2.444k in   5.041748s
pipelined: pooled    506.902  (±11.4%) i/s -      2.499k in   5.023392s
pipelined: envoy    509.337  (±11.0%) i/s -      2.550k in   5.079907s
pipelined: cproxy    406.835  (±16.0%) i/s -      2.006k in   5.081378s
Comparison:
pipelined: envoy:      509.3 i/s
pipelined: pooled:      506.9 i/s - …
```
> ci: benchmark should be fair

- README.md
- lib/redis_client/cluster.rb
- lib/redis_client/cluster/concurrent_worker.rb
- lib/redis_client/cluster/concurrent_worker/none.rb
- lib/redis_client/cluster/concurrent_worker/on_demand.rb
- lib/redis_client/cluster/concurrent_worker/pooled.rb
- lib/redis_client/cluster_config.rb
- test/ips_pipeline.rb
- test/redis_client/cluster/concurrent_worker/test_none.rb
Oh my gosh
```
pipelined: ondemand    46.000  i/100ms
pipelined: pooled    52.000  i/100ms
pipelined: none    49.000  i/100ms
pipelined: envoy    46.000  i/100ms
pipelined: cproxy    39.000  i/100ms
pipelined: ondemand    463.272  (± 8.0%) i/s -      2.300k in   5.011685s
pipelined: pooled    505.496  (± 8.1%) i/s -      2.548k in   5.094204s
pipelined: none    489.561  (± 9.6%) i/s -      2.450k in   5.072220s
pipelined: envoy    516.512  (±11.4%) i/s -      2.576k in   5.080221s
pipelined: cproxy    414.037  (±13.5%) i/s - …
```
> fix: rename option for concurrency

- README.md
- lib/redis_client/cluster.rb
- lib/redis_client/cluster/router.rb
- lib/redis_client/cluster/transaction.rb
- test/redis_client/test_cluster.rb
* https://github.com/redis/redis-rb/issues/1224
> feat: support transaction

- lib/redis_client/cluster/node.rb
- test/ips_slot_array.rb
- test/ips_slot_node_mapping.rb
- test/redis_client/cluster/test_node.rb
```
CharArray   783.598k i/100ms
Array     1.849M i/100ms
CharArray      7.804M (± 2.4%) i/s -     39.180M in   5.024004s
Array     18.948M (± 3.8%) i/s -     96.166M in   5.083967s
Comparison:
Array: 18947756.4 i/s
CharArray:  7803935.6 i/s - 2.43x  slower
```
```
pipelined: ondemand    50.000  i/100ms
pipelined: pooled …
```
> perf: add an environment variable to be able to configure a data type of slots and nodes mapping

- lib/redis_client/cluster/command.rb
- lib/redis_client/cluster/node.rb
- lib/redis_client/cluster/pub_sub.rb
- lib/redis_client/cluster/router.rb
* This PR relates to:
* #286
* Add `REDIS_CLIENT_SLOW_COMMAND_TIMEOUT` to environment variables
* It's used with calling `CLUSTER NODES` and `COMMAND` if specified.
* Use replicas instead of primaries when sending `COMMAND` command
* But it depends on the topology.
> perf: reduce load of servers in initialization as possible

- README.md
- lib/redis_client/cluster/command.rb
- lib/redis_client/cluster/node.rb
- lib/redis_client/cluster/router.rb
- lib/redis_client/cluster_config.rb
- test/redis_client/cluster/test_command.rb
Thank you so much for your work on https://github.com/redis-rb/redis-cluster-client/issues/286 which addressed adding an override for `slow` commands.
This builds upon that and adds a configuration option for this timeout that can be passed directly to the client. This will allow the option to be contained within the client configuration and remove the need to specify any environment variables outside of said configuration.
> Make SLOW_COMMAND_TIMEOUT a configuration option

- README.md
- lib/redis_client/cluster/router.rb
- lib/redis_client/cluster_config.rb
When using a DNS endpoint and all of the underlying host IPs are changed, this can cause continuous connection errors, as the node list is fetched during initialization and then not refreshed from the original DNS endpoint. We've had this happen during Elasticache maintenance when all underlying nodes in the clusters are slowly replaced.
This adds a new configuration option that allows the original configuration that was used for cluster discovery to be used when we receive and error and refresh the node list. We've had a patch that does something similar to this in our current version of redis-rb (4.8) but we're working on migrating to 5.x and would like to upstream this if possible.
I was able to run the tests locally and everything is passing but it was unclear to me how exactly to …
> Adds new configuration option to specify reconnecting using the original configuration options when refreshing nodes

- test/ips_concurrent_worker.rb
- test/redis_client/cluster/concurrent_worker/mixin.rb
* #302
* Receivers aren't hash objects.
> ci: appease rubocop

- test/command_capture_middleware.rb
- test/redis_client/test_cluster.rb
- test/testing_helper.rb
This PR adds some tooling for capturing the actual executed redis commands during tests. It's not yet used in this PR, but this should be of assistance when writing the tests for `#with` and `#multi` behaviour.
> Add infrastructure for capturing Redis commands in tests

- .rubocop.yml
- README.md
- lib/redis_client/cluster.rb
- test/redis_client/test_cluster.rb
This PR actually implements the #with method for checking out a connection directly to a particular Redis node. This allows you to perform transactional commands directly against the underlying `RedisClient` instance, so `#watch`, `#multi`, etc all work.
This does NOT yet implement any kind of validation for the commands issued. If you issue commands involving keys not owned by the node, you will receive `Redis::CommandError`'s. A future PR will add client-side validation to hopefully make it possible to catch problems related to transaction misuse earlier in development. There's a pending test for this.
This PR also does not yet implement `RedisClient::Cluster#multi` in terms of `#with`. That will also come in a future PR.
>  Implement RedisClient::Cluster#with (again!)

- .github/workflows/release.yaml
- README.md
> ci: add a workflow for release

- lib/redis_client/cluster.rb
- lib/redis_client/cluster/router.rb
- lib/redis_client/cluster/transaction.rb
- test/redis_client/test_cluster.rb
- test/test_against_cluster_state.rb
* This isn't an intended behavior because of the cutting corners in the following pull request.
* #277
* Although there is a discussion for the design regarding `#with` and `#multi` method implementations, this behavior should be fixed in advance because it's certainly a bug.
* #299
> fix: don't call the block twice during the transaction

- lib/redis_client/cluster/transaction.rb
- test/redis_client/test_cluster.rb
- test/test_against_cluster_state.rb
The test case is not enough and I found that the implementation of the handling replies for the transaction is corrupted.
> test: ensure the transaction is legit durling the resharding

- README.md
- lib/redis_client/cluster.rb
- lib/redis_client/cluster/node_key.rb
- lib/redis_client/cluster/optimistic_locking.rb
- lib/redis_client/cluster/transaction.rb
- test/redis_client/cluster/test_node_key.rb
- test/redis_client/test_cluster.rb
* #299
* #318
* It was degraded since the above fixing.
> fix: the watch command should be executed in advance out of the pipeline of the transaction

- lib/redis_client/cluster.rb
- lib/redis_client/cluster/optimistic_locking.rb
- lib/redis_client/cluster/transaction.rb
- test/test_against_cluster_state.rb
* #299
* #325
* It was degraded since the above fixing.
> fix: cluster client should be able to handle redirection for the watch command

- lib/redis_client/cluster.rb
- lib/redis_client/cluster/optimistic_locking.rb
- lib/redis_client/cluster/router.rb
- lib/redis_client/cluster/transaction.rb
> fix: use the slot for the validation in the transaction

- lib/redis_client/cluster/router.rb
- test/redis_client/test_cluster.rb
> fix: make an error message easy to understand for the watch command

- lib/redis_client/cluster.rb
- lib/redis_client/cluster/optimistic_locking.rb
- lib/redis_client/cluster/transaction.rb
- test/redis_client/test_cluster.rb
- test/test_against_cluster_state.rb
This PR contains two commits which each fix an aspect of retry handling with WATCH/MULTI.
---
First patch:  https://github.com/redis-rb/redis-cluster-client/commit/954668291e665a59e264f906355fa86f064abf37
* It's important that all of a transaction actually happens on the same connection, with no transparent reconnection allowed inside ::RedisClient. So, we wrap a watch transaction in ensure_connected_cluster_scoped(retryable: false).
* We don't need to call UNWATCH on connection errors (since the connection state is already broken). redis-rb and RedisClient don't do this either.
---
Second patch: https://github.com/redis-rb/redis-cluster-client/commit/99de3d3b06deeb0a598b2d8a3308b89bf55d8401
If we have a WATCH, then the MULTI _must_ exec on exactly that node; it should not be allowed for …
> Fix two separate but related problems with watch retry handling

- test/cluster_controller.rb
```
TestAgainstClusterScale#test_02_scale_in:
RedisClient::CommandError: ERR Please use SETSLOT only with masters. (redis://127.0.0.1:6385)
vendor/bundle/ruby/3.3.0/gems/redis-client-0.21.0/lib/redis_client/connection_mixin.rb:36:in `call'
vendor/bundle/ruby/3.3.0/gems/redis-client-0.21.0/lib/redis_client.rb:279:in `block (2 levels) in call'
vendor/bundle/ruby/3.3.0/gems/redis-client-0.21.0/lib/redis_client/middlewares.rb:16:in `call'
vendor/bundle/ruby/3.3.0/gems/redis-client-0.21.0/lib/redis_client.rb:278:in `block in call'
vendor/bundle/ruby/3.3.0/gems/redis-client-0.21.0/lib/redis_client.rb:699:in `ensure_connected'
vendor/bundle/ruby/3.3.0/gems/redis-client-0.21.0/lib/redis_client.rb:277:in `call'
test/cluster_controller.rb:147:in `block in finish_resharding'
```
Although it's a bad …
> test: fix a error handling bug

- lib/redis_client/cluster/router.rb
> fix: fix a dedicated method for watch to be the same manner as the multi method

- lib/redis_client/cluster.rb
- lib/redis_client/cluster/pipeline.rb
- test/redis_client/test_cluster.rb
* https://github.com/redis-rb/redis-client/issues/28
* #297
* https://github.com/redis-rb/redis-client/pull/187
> feat: add an option to the pipeline feature to be able to select either throwing an error or returning errors as is

- lib/redis_client/cluster/error_identification.rb
- lib/redis_client/cluster/node.rb
- lib/redis_client/cluster/router.rb
- test/redirection_emulation_middleware.rb
- test/redis_client/test_cluster.rb
- test/testing_helper.rb
* #310
* I doubt whether every user needs the error identification middleware or not. I think our 99% users don't use this library in a nested block against multiple clusters. Also, middlewares are called every time by commands and pipelines. It affects the performance in no small measure.
* The node class doesn't need any dependencies with the middleware. So we should decouple them. The middleware is used by only the router class.
> fix: make the error identification middleware optional because of the use case

- lib/redis_client/cluster/node.rb
> /home/runner/work/redis-cluster-client/redis-cluster-client/lib/redis_client/cluster/node.rb:427: warning: instance variable @last_reloaded_at not initialized
> fix: a not initialized instance variable warned on Ruby 2.7

- lib/redis_client/cluster/transaction.rb
- test/redis_client/test_cluster.rb
It  should be behaved as the same as redis-client.
https://github.com/redis-rb/redis-client/blob/d895cf32ffe779d2c6692e1006947ed9c0eb63a0/lib/redis_client.rb#L445-L477
> fix: return empty array if the transaction is empty

- lib/redis_client/cluster/command.rb
- lib/redis_client/cluster/router.rb
- test/redis_client/cluster/test_command.rb
- test/redis_client/test_cluster.rb
It might be useful. Although there may be more, we are going to support `MSET`, `MGET` and `DEL` so far.
> feat: prevent a cross slot error by using pipelining when calling a command with multiple keys

- .github/workflows/test.yaml
- lib/redis_client/cluster/router.rb
- test/ips_mget.rb
- test/prof_mem.rb
- test/prof_stack.rb
* #356
```
allocated memory by gem
14959968  redis-client-0.22.1
14496373  redis-cluster-client/lib
120832  other
80439  socket
11472  uri
```
```
allocated memory by gem
13359968  redis-client-0.22.1
6496373  redis-cluster-client/lib
120832  other
63891  socket
11472  uri
```
```
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
MGET: original   313.000 i/100ms
MGET: emulated    54.000 i/100ms
MGET: original      3.083k (±10.0%) i/s -     15.337k in   5.049041s
MGET: emulated    521.688 (± 8.8%) i/s -      2.592k in   5.013249s
Comparison:
MGET: original:     3083.2 i/s
MGET: emulated:      521.7 i/s - 5.91x …
```
> perf: lessen memory consumption for emulated mget command

- test/ips_mget.rb
- test/redis_client/test_cluster.rb
```
ruby 3.3.1 (2024-04-23 revision c56cd86388) [x86_64-linux]
MGET: original   670.000 i/100ms
MGET: emulated    99.000 i/100ms
MGET: single_get    30.000 i/100ms
MGET: original      6.880k (± 6.7%) i/s -     34.840k in   5.093497s
MGET: emulated    984.077 (± 6.1%) i/s -      4.950k in   5.057650s
MGET: single_get    317.817 (± 4.4%) i/s -      1.590k in   5.012359s
Comparison:
MGET: original:     6880.2 i/s
MGET: emulated:      984.1 i/s - 6.99x  slower
MGET: single_get:      317.8 i/s - 21.65x  slower
```
> ci: add a case to the test for the iteration per second

- lib/redis_client/cluster/key_slot_converter.rb
- lib/redis_client/cluster/router.rb
- test/redis_client/cluster/test_key_slot_converter.rb
```
allocated memory by gem
5506464  redis-client-0.22.1
435368  redis-cluster-client/lib
70110  socket
10672  uri
1072  other
```
```
allocated memory by location
1640720  redis-client-0.22.1/lib/redis_client/ruby_connection/resp3.rb:99
1027840  redis-client-0.22.1/lib/redis_client/ruby_connection/resp3.rb:54
976160  redis-client-0.22.1/lib/redis_client/command_builder.rb:9
788688  redis-client-0.22.1/lib/redis_client/ruby_connection/resp3.rb:189
488440  redis-client-0.22.1/lib/redis_client/ruby_connection/resp3.rb:38
187440  redis-client-0.22.1/lib/redis_client/ruby_connection/buffered_io.rb:32
175840  redis-client-0.22.1/lib/redis_client/ruby_connection/resp3.rb:175
160000 …
```
> perf: lessen memory consumptions in a emulated mget method

- lib/redis_client/cluster/command.rb
- lib/redis_client/cluster/router.rb
- test/redis_client/cluster/test_command.rb
- test/redis_client/test_cluster.rb
for the tiny little performance improvement
> chore: use hard coding instead of using command information

- compose.yaml
- test/testing_constants.rb
* #89
* #354
```
$ docker compose up
$ docker compose exec ruby bundle install
$ docker compose exec ruby bundle exec rake test
```
This is just an workaround. I'd like to improve the test environment to be simple and easy to use for everyone in the future. I think the current setting is complex and awkward.
> chore: add a ruby container to docker compose for macOS users

- lib/redis_client/cluster.rb
- test/redis_client/test_cluster.rb
- test/test_against_cluster_broken.rb
- test/test_against_cluster_scale.rb
- test/test_against_cluster_state.rb
* https://github.com/redis/redis-rb/issues/1276
> fix: delay initialization to the first query

- .github/workflows/test.yaml
- compose.valkey.yaml
- test/benchmark_helper.rb
- test/benchmark_mixin.rb
- test/cluster_controller.rb
- test/redis_client/test_cluster.rb
- test/test_against_cluster_broken.rb
- test/test_against_cluster_scale.rb
- test/test_against_cluster_state.rb
- test/testing_helper.rb
* https://github.com/redis-rb/redis-client/pull/197
The above fixing made our several test cases slow. So we should've shorten the time by any workaround. 
Also, in experimental, I added a test case for Valkey server. The following fixing gave us a stability in a resharding state. But I'll leave our resharding test cases alone for now.
* https://github.com/valkey-io/valkey/pull/495
> ci: shorten blocking timeout seconds, add a test case for Valkey

- test/redis_client/test_cluster.rb
```
1) Failure:
RedisClient::TestCluster::ScaleReadRandom#test_dedicated_multiple_keys_command [test/redis_client/test_cluster.rb:732]:
8.
Expected: ["val1", "val2"]
Actual: ["val1", nil]
```
It's just a replication delay.
> ci: fix a flaky test case

- README.md
- lib/redis_client/cluster/node.rb
- lib/redis_client/cluster_config.rb
- test/redis_client/cluster/test_node.rb
This PR proposes to let users configure individual `RedisClient::Cluster` instances using `max_startup_sample`.
A single application could connect to multiple Redis Clusters of different sizes. Using a single global envvar would mean we either over-sample on small clusters or under-sample on large clusters.
> feat: introduce max_startup_sample in ClusterConfig

- Gemfile
- test/ips_single.rb
https://github.com/socketry/async-redis
```
ruby 3.3.4 (2024-07-09 revision be1089c8ec) [x86_64-linux]
single: cli   118.000 i/100ms
single: envoy    36.000 i/100ms
single: cproxy    53.000 i/100ms
single: cli      1.195k (± 5.7%) i/s -      6.018k in   5.053942s
single: envoy    367.100 (± 3.8%) i/s -      1.872k in   5.107732s
single: cproxy    531.992 (± 2.3%) i/s -      2.703k in   5.083637s
Comparison:
single: cli:     1194.9 i/s
single: cproxy:      532.0 i/s - 2.25x  slower
single: envoy:      367.1 i/s - 3.26x  slower
ruby …
```
> ci: add async-redis to iterations per second for a benchmark

- README.md
These behaviors were changed since [v0.9.0](https://github.com/redis-rb/redis-cluster-client/releases/tag/v0.9.0).
> docs: fix readme about MGET, MSET and DEL commands

- .github/workflows/test.yaml
- Rakefile
- compose.valkey.yaml
- test/test_against_cluster_state.rb
* https://github.com/redis/redis/issues/11312
* https://github.com/valkey-io/valkey/pull/495
Since Valkey has been fixed the bug, now we can test the resharding behavior with replicas.
> test: resume resharding test for scale reading

- lib/redis_client/cluster/node.rb
- lib/redis_client/cluster/router.rb
- test/middlewares/redirect_count.rb
- test/middlewares/redirect_fake.rb
- test/redis_client/test_cluster.rb
- test/test_against_cluster_broken.rb
- test/test_against_cluster_scale.rb
- test/test_against_cluster_state.rb
- test/testing_helper.rb
The following commands are slow query.
* https://redis.io/docs/latest/commands/cluster-nodes/
* https://redis.io/docs/latest/commands/cluster-slots/
* https://redis.io/docs/latest/commands/cluster-shards/
So clients should care about load of servers.
* [Redis OSS cluster client discovery and exponential backoff](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/BestPractices.Clients.Redis.Discovery.html)
This pull request mitigates it.
* #368
> perf: lessen reload frequency to mitigate load of servers

- README.md
- test/test_against_cluster_broken.rb
- test/test_against_cluster_scale.rb
- test/test_against_cluster_state.rb
- test/testing_helper.rb
> test: count errors of cluster down

- .github/workflows/test.yaml
- .rubocop.yml
- lib/redis_client/cluster/errors.rb
- lib/redis_client/cluster/optimistic_locking.rb
- lib/redis_client/cluster/pipeline.rb
- lib/redis_client/cluster/pub_sub.rb
- lib/redis_client/cluster/router.rb
- lib/redis_client/cluster/transaction.rb
- test/cluster_controller.rb
- test/redis_client/cluster/test_errors.rb
- test/redis_client/cluster/test_node.rb
- test/redis_client/test_cluster.rb
- test/test_against_cluster_scale.rb
- test/test_against_cluster_state.rb
Several kinds of errors may be a sign of the time to renew the cluster state information in our client. So that we should handle these errors and update the state to prevent continuously throwing them. Also, we can retry a process as possible internally.
A portion of this fix is related to the following:
* #368
> fix: ensure recoverability from cluster state changes

- bin/pubsub
- bin/singlepiptx
- lib/redis_client/cluster/errors.rb
- lib/redis_client/cluster/optimistic_locking.rb
- lib/redis_client/cluster/pipeline.rb
- lib/redis_client/cluster/pub_sub.rb
- lib/redis_client/cluster/router.rb
- lib/redis_client/cluster/transaction.rb
- test/redis_client/cluster/test_errors.rb
- test/test_against_cluster_scale.rb
The following fix was insufficient.
* #379
* #381
* #383
Also the following issue is related.
* #368
> fix: insufficient error handling for cluster down

- .github/workflows/test.yaml
- compose.valkey.yaml
- test/test_against_cluster_broken.rb
Although this way may not work for macOS, I'd like to expand on our test cases by an easy way with Docker.
* #354
That said, this test case is too slow.
> test: add a case for node recovery in a broken cluster

- .github/workflows/test.yaml
- test/cluster_controller.rb
- test/test_against_cluster_broken.rb
- test/test_against_cluster_down.rb
>  test: fix cluster broken case

- .github/workflows/test.yaml
- bin/pubsub
- bin/singlepiptx
- lib/redis_client/cluster.rb
- lib/redis_client/cluster/node.rb
- test/redis_client/test_cluster.rb
- test/test_against_cluster_down.rb
* refactor some debug tools
* refactor some test cases
* make `RedisClient::Cluster.new` possible
* use `call_once` instead of `call` with `CLUSTER NODES`
> chore: patch some minor changes

- lib/redis_client/cluster/pub_sub.rb
* Don't clear subscribed messages while recovering subscriptions to prevent lost backlogs.
* Sleep some duration for mitigating CPU consumption while repeating the same error such as ConnectionError.
> fix: the behavior of subscription in pubsub when nodes are unstable

- lib/redis_client/cluster/optimistic_locking.rb
- lib/redis_client/cluster/router.rb
- test/cluster_controller.rb
- test/test_against_cluster_broken.rb
If we catch a connection error and refresh the cluster topology, we need to re-calculate what node to send the command to in the router; the node we're using might not even be a valid node any longer.
I added two test cases to test_against_cluster_broken.rb which demonstrate this; one with a transaction, and one without. In both cases, without the patch, the first command after a node goes down fails because the client realises it needs to fetch new node info (with `update_cluster_info!`), but then retries the command on the old node still (which doesn't even exist anymore). The patch fixes this.
Unfortunately these tests won't pass on CI at the moment because of #354 but they work on my machine if you run them by themseles (with `bundle exec ruby -Itest …
> Assign a new node after calling update_cluster_info!

- .gitignore
- Gemfile
- lib/redis_client/cluster.rb
- lib/redis_client/cluster/noop_command_builder.rb
- lib/redis_client/cluster/pipeline.rb
- lib/redis_client/cluster/router.rb
- lib/redis_client/cluster/transaction.rb
- lib/redis_client/cluster_config.rb
- test/prof_stack2.rb
- test/redis_client/test_cluster.rb
- test/redis_client/test_cluster_config.rb
> perf: command builder shouldn't be called multiple times

- lib/redis_client/cluster/errors.rb
> `warning: instance variable @errors not initialized`
It is warned on Ruby 2.7.
> fix: instance variable @errors not initialized

- README.md
- lib/redis_client/cluster/concurrent_worker.rb
- lib/redis_client/cluster/concurrent_worker/on_demand.rb
- lib/redis_client/cluster/concurrent_worker/pooled.rb
- lib/redis_client/cluster_config.rb
- test/redis_client/test_cluster_config.rb
```
ruby 3.3.6 (2024-11-05 revision 75015d4c1f) [x86_64-linux]
pipelined: ondemand    72.000 i/100ms
pipelined: pooled    82.000 i/100ms
pipelined: none    84.000 i/100ms
pipelined: envoy    80.000 i/100ms
pipelined: cproxy    39.000 i/100ms
pipelined: ondemand    715.452 (± 6.6%) i/s    (1.40 ms/i) -      3.600k in   5.064794s
pipelined: pooled    830.765 (± 0.7%) i/s    (1.20 ms/i) -      4.182k in   5.034200s
pipelined: none    846.257 (± 5.8%) i/s    (1.18 ms/i) -      4.284k in   5.084215s
pipelined: envoy    805.275 (± 7.0%) i/s    (1.24 ms/i) -      4.000k in   5.007049s
pipelined: cproxy    400.326 (± 5.2%) i/s    (2.50 ms/i) -      2.028k in   5.085483s
Comparison:
pipelined: none: …
```
> fix: make no-concurrency mode default

- lib/redis_client/cluster/pipeline.rb
- lib/redis_client/cluster/router.rb
> perf: lessen conditional branches

- lib/redis_client/cluster.rb
- lib/redis_client/cluster/router.rb
No need to be an instance variable.
> perf: make dedicated actions definition static

- lib/redis_client/cluster/node/base_topology.rb
With a single-node cluster, this fixes a failure whereby the client attempts to issue a READONLY command to the sole master. This returns an unknown command error with Redis Enterprise Cloud.
> Fixes initial topology

- lib/redis_client/cluster/errors.rb
- lib/redis_client/cluster/router.rb
- lib/redis_client/cluster_config.rb
Since Ractor is still an experimental feature, I won't write any test cases yet.
> fix: make constant value shareable with Ractor

- lib/redis_client/cluster/concurrent_worker/pooled.rb
> fix: interruption handling in worker thread
